### ISSUE TITLE
Abe fails to grab ledge when run jumping from afar, but succeeds when run jumping close up.

### ISSUE THREAD

**Issue by AvengingGibbons** [AliveTeam/alive_reversing#14] opened 2018-12-23 16:59 UTC
[necrum ledge.zip](https://github.com/AliveTeam/alive_reversing/files/2706140/necrum.ledge.zip)

**Comment by mouzee1337** [comment] 2018-12-23 17:05
its already fixed DansGame

**Comment by paulsapps** [comment] 2018-12-23 18:12
Probably duplicate of #6

**Closed by paulsapps** 2018-12-23 18:12 UTC

**Comment by mouzee1337** [comment] 2018-12-23 18:13
> Probably duplicate of #6

yup can confirm
