### ISSUE TITLE
AE Rev Bug - BRP21C01 - Game crashes when you free mudokons and fleeches are trying to eat them.

### ISSUE THREAD

**Issue by ViWalls** [AliveTeam/alive_reversing#1568] opened 2022-09-12 21:03 UTC
Found in build: 4604
Last working build number: NONE

Description of issue:
If leeches are attacking mudokons when escaping through portal the game crashes.

Steps to repro:
Just guide mudokons to portal screen, place yourself in a safe spot like top left and then say "work" to the one is near the lever. Now chant and wait until crash.
[SLURM.zip](https://github.com/AliveTeam/alive_reversing/files/9551811/SLURM.zip)

**Comment by mouzedrift** [comment] 2022-09-12 21:09
duplicate of #358 (and also an OG bug)

**Closed by mouzedrift** 2022-09-12 21:09 UTC
Labels: AE rev bug
